const actionTypes = {
    GET_BANNER_START: 'GET_BANNER_START',
    GET_BANNER_SUCCESS: 'GET_BANNER_SUCCESS',
    GET_BANNER_FAILED: 'GET_BANNER_FAILED',

    SET_CURRENT_SONG_ID: 'SET_CURRENT_SONG_ID',

    SET_PLAYING_SONG: 'SET_PLAYING_SONG'
};

export default actionTypes;