const actionTypes = {
    GET_HOME_START: 'GET_HOME_START',
    GET_HOME_SUCCESS: 'GET_HOME_SUCCESS',
    GET_HOME_FAILED: 'GET_HOME_FAILED',

    SET_IS_PLAYING: 'SET_IS_PLAYING',

    SET_CURRENT_SONG_ID: 'SET_CURRENT_SONG_ID',

    SET_CURRENT_SONG_DATA: 'SET_CURRENT_SONG_DATA',

    SET_RECENT_SONGS: 'SET_RECENT_SONGS',

    SET_KEYWORD: 'SET_KEYWORD',

    SET_PLAYLIST_START: 'SET_PLAYLIST_START',
    SET_PLAYLIST_SUCCESS: 'SET_PLAYLIST_SUCCESS',
    SET_PLAYLIST_FAILED: 'SET_PLAYLIST_FAILED',

    SEARCH_DATA_START: 'SEARCH_DATA_START',
    SEARCH_DATA_SUCCESS: 'SEARCH_DATA_SUCCESS',
    SEARCH_DATA_FAILED: 'SEARCH_DATA_FAILED',

    SET_ARTIST_SONGS_START: 'SET_ARTIST_SONGS_START',
    SET_ARTIST_SONGS_SUCCESS: 'SET_ARTIST_SONGS_SUCCESS',
    SET_ARTIST_SONGS_FAILED: 'SET_ARTIST_SONGS_FAILED',
};

export default actionTypes;