const actionTypes = {
    GET_HOME_START: 'GET_HOME_START',
    GET_HOME_SUCCESS: 'GET_HOME_SUCCESS',
    GET_HOME_FAILED: 'GET_HOME_FAILED',

    SET_IS_PLAYING: 'SET_IS_PLAYING',

    SET_CURRENT_SONG_ID: 'SET_CURRENT_SONG_ID',

    SET_CURRENT_SONG_DATA: 'SET_CURRENT_SONG_DATA',

    SET_RECENT_SONGS: 'SET_RECENT_SONGS',

    SET_PLAYLIST_START: 'SET_PLAYLIST_START',
    SET_PLAYLIST_SUCCESS: 'SET_PLAYLIST_SUCCESS',
    SET_PLAYLIST_FAILED: 'SET_PLAYLIST_FAILED',
};

export default actionTypes;